version: '3.8'

services:
  # Backend API service
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URI=sqlite:///instance/app.db
      # Add other environment variables from .env file
    env_file:
      - ./backend/.env
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 